# ansible-playbook -i playbook_test/inventory_host_dds.yml playbook_test/playbook_for_module_huawei_olt_config_service_port.yml
- name: TEST MULTIPOLAR MODULE OLT DISPLAY VLAN
  hosts: huawei_olt
  connection: local
  gather_facts: no
  vars:
    originate_vlan: '3002'
    designated_vlan: '3001'
    target_gemindex: '2'

  tasks:
    - name: Get all service port that use vlan {{originate_vlan}}
      multipolar_huawei_olt_command_display_service_port:
        service_port_vlan: '{{originate_vlan}}'
        ansible_host: '{{ hostvars[inventory_hostname].ansible_host }}'
        ansible_network_os: '{{ hostvars[inventory_hostname].ansible_network_os }}'
        ansible_platform: '{{ hostvars[inventory_hostname].ansible_platform }}'
        ansible_user: '{{ hostvars[inventory_hostname].ansible_user }}'
        ansible_ssh_pass: '{{ hostvars[inventory_hostname].ansible_ssh_pass }}'
      register: output
      
    - name: Undo existing service-port and push new service-port with new VLAN - {{designated_vlan}}
      multipolar_huawei_olt_config_service_port:
        command_undo: 'undo service-port {{item.index}}'
        command_set: 'service-port {{item.index}} vlan {{ designated_vlan }} gpon  {{item.frameslot}}{{item.port}} ont {{item.vpi}} gemport {{target_gemindex}} multi-service user-vlan {{item.flowpara}} tag-transform translate inbound traffic-table index {{item.tx}} outbound traffic-table index {{item.rx}}'
        ansible_host: '{{ hostvars[inventory_hostname].ansible_host }}'
        ansible_network_os: '{{ hostvars[inventory_hostname].ansible_network_os }}'
        ansible_platform: '{{ hostvars[inventory_hostname].ansible_platform }}'
        ansible_user: '{{ hostvars[inventory_hostname].ansible_user }}'
        ansible_ssh_pass: '{{ hostvars[inventory_hostname].ansible_ssh_pass }}'
      with_items: '{{ output.return_from_devices }}'