# ansible-playbook -i playbook_test/inventory_host_dds.yml playbook_test/playbook_for_read_vars_from_files.yml 
- name: READ VARIABLE FROM FILES
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  - name: read files
    include_vars:
      file: /opt/public_var_ansible/var_vlan_desc
      name: vlan_desc
  
  - name: print that
    debug:
      msg: '{{item.vlan}}'
    when: item.desc is search("SPEEDY")
    with_items: '{{ vlan_desc.return_from_devices }}'
