# ansible-playbook -i playbook_test/inventory_host_dds.yml playbook_test/playbook_for_module_huawei_display_ip_routing_table.yml 
- name: TEST MULTIPOLAR MODULE
  hosts: metro_service1
  connection: local
  gather_facts: no

  tasks:
    - name: RUN CALL HUAWEI MODULE
      multipolar_module_huawei_display_ip_routing_table:
        command: 'display ip routing-table'
        ansible_host: '{{ hostvars[inventory_hostname].ansible_host }}'
        ansible_network_os: '{{ hostvars[inventory_hostname].ansible_network_os }}'
        ansible_user: '{{ hostvars[inventory_hostname].ansible_user }}'
        ansible_ssh_pass: '{{ hostvars[inventory_hostname].ansible_ssh_pass }}'
        ansible_platform: '{{ hostvars[inventory_hostname].ansible_platform }}'
      register: output

    - name: PRINT OUTPUT SUCCESS MODULE
      debug:
        msg: '{{ output }}'